# hyprlang noerror false
# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# UNSET – må matche nøyaktig
gesture = 3, pinch, unset
gesture = 3, swipe, unset
gesture = 4, horizontal, unset
gesture = 4, up, unset
gesture = 4, down, unset

gesture = 4, swipe, move,
gesture = 3, pinch, fullscreen, maximize
gesture = 3, horizontal, workspace
gesture = 3, down, dispatcher, exec, /home/Enki/.config/hypr/custom/scripts/workspace_by_10 up
gesture = 3, up, dispatcher, exec, /home/Enki/.config/hypr/custom/scripts/workspace_by_10 down


input {
    kb_layout  = us,us,us,no,
    kb_variant = ,dvorak,dvp,
    kb_options = grp:win_space_toggle
    touchpad {
        clickfinger_behavior = false
	disable_while_typing = false
	# natural_scroll = false
    }
}


misc {
    disable_autoreload = false
}
