# hyprlang noerror false
# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User
bind = Ctrl+Super, Slash, exec, xdg-open ~/.config/illogical-impulse/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds

# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above

# Power-button → session menu (quickshell + fallback)
bindd = , XF86PowerOff, Toggle session menu, global, quickshell:sessionToggle # [hidden] Toggle session menu
bind  = , XF86PowerOff, exec, qs -c $qsConfig ipc call TEST_ALIVE || pkill wlogout || wlogout -p layer-shell # [hidden] Session menu (fallback)

# bind=SUPER,P,exec,~/.config/hypr/custom/scripts/toggle-display.sh # Switch display mode

bind = Ctrl+Alt+Shift, L, exec, lizard # Play Lizard soundclip

#bind = Alt, Tab, cyclenext # Cycle active window
#bind = Alt, Tab, bringactivetotop, # [hidden] bring it to the top

#bind = ALT, Tab, exec, hyprctl --batch "dispatch cyclenext; dispatch bringactivetotop"
bind = ALT, Tab, exec, ~/.config/hypr/custom/scripts/alttab-cycle-copy-state.sh # Cycle active window


# bind = Ctrl, Space, global, :hypr-menu # Use Kando menu 

# bind = SUPER, SPACE, exec, hyprctl switchxkblayout at-translated-set-2-keyboard next # Cycle keyboard layout
# bind = SUPER SHIFT, SPACE, exec, hyprctl switchxkblayout at-translated-set-2-keyboard prev # Cycle keyboard layout (reverse)
