#!/usr/bin/env bash

#
# ~/.config/shell/bashrc.d/history
#

HISTSIZE=10000
HISTFILESIZE=20000
export HISTCONTROL=ignorespace:erasedups
shopt -s histappend
function historymerge {
    history -n; history -w; history -c; history -r;
}
trap historymerge EXIT
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
