# .chezmoidata/ignores-hypr.toml

[ignore.hyprland.paths]
base = [
  ".config/hypr/",
  ".config/hypr/**",
  ".config/waybar/",
  ".config/waybar/**",
  ".config/hyprpaper/",
  ".config/hyprpaper/**",
  ".config/hypridle/",
  ".config/hypridle/**",
  ".config/hyprlock/",
  ".config/hyprlock/**",
  ".config/zshrc.d/auto-Hypr.sh",
  ".config/bashrc.d/auto-Hypr.sh",
  ".config/bashrc.d/dots-hyprland.zsh",
  ".config/bashrc.d/auto-Hypr.sh",
  ".config/fish/auto-Hypr.fish",
]

kooldots = [
  ".config/ags/",
  ".config/ags/**",
]

illogical_impulse = [
  ".config/quickshell/",
  ".config/quickshell/**",
  ".config/illogical-impulse/",
  ".config/illogical-impulse/**",
]